// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // El CLI (migrate/db seed/studio) necesita una conexión directa, no la
    // agrupada con pgbouncer: Supabase (y cualquier pooler en modo
    // transacción) no admite DDL/migraciones a través del pool. En local/
    // Docker no hay distinción real, así que DIRECT_URL cae de vuelta a
    // DATABASE_URL. Ver docs/DEPLOYMENT.md.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
